"""empty message

Revision ID: 85f8b92191c8
Revises: 31fe4acde89e
Create Date: 2021-03-03 20:54:25.860262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f8b92191c8'
down_revision = '31fe4acde89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acao', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acao', 'last_updated')
    # ### end Alembic commands ###
