"""empty message

Revision ID: c5b9f134cdae
Revises: c6bdb86b676a
Create Date: 2021-03-13 13:36:45.438607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b9f134cdae'
down_revision = 'c6bdb86b676a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acao', sa.Column('isbank', sa.Integer(), nullable=True))
    op.drop_column('acao', 'industry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acao', sa.Column('industry', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('acao', 'isbank')
    # ### end Alembic commands ###
