"""empty message

Revision ID: c6bdb86b676a
Revises: 85f8b92191c8
Create Date: 2021-03-13 13:19:09.296367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bdb86b676a'
down_revision = '85f8b92191c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acao', sa.Column('industry', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acao', 'industry')
    # ### end Alembic commands ###
